advicehealth/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carford.urls'))
]

carford/urls.py
app_name = 'carford'

from django.urls import path
from .views import *

urlpatterns = [
    path('', Dashboard,name='dashboard'),
    path('person/add/', PersonCreateView.as_view(),name='add_pessoa'),
    path('car/add/', CarCreateView.as_view(),name='add_carro'),
]

carford/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Person(models.Model):
    nome = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.nome)

class Car(models.Model):
    COLOR_CHOICES = (
        ('Amarelo','Amarelo'),
        ('Azul','Azul'),
        ('Cinza','Cinza')
    )
    TYPE_CHOICES = (
        ('Hatch','Hatch'),
        ('Sedan','Sedan'),
        ('Conversível','Conversível')
    )
    pessoa = models.ForeignKey(Person,on_delete=models.CASCADE,related_name="person_car")
    cor = models.CharField(max_length=50,choices=COLOR_CHOICES)
    modelo = models.CharField(max_length=50,choices=TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.modelo,self.cor)
    
    def clean(self):
        cor = Car.objects.filter(pessoa_id=self.pessoa_id,cor=self.cor)
        modelo = Car.objects.filter(pessoa_id=self.pessoa_id,modelo=self.modelo)
        if cor or modelo:
            raise ValidationError('{} já tem cor ou modelo desse tipo'.format(self.pessoa))            
        if Car.objects.filter(pessoa_id=self.pessoa_id).count() >= 3:
            raise ValidationError('{} já tem o máximo de carros permitidos'.format(self.pessoa))
    
    def save(self, *args, **kwargs):
        self.full_clean()
        return super().save(*args, **kwargs)

teste/models.py
from django.db import models
from django.core.exceptions import ValidationError

# Create your models here.
class Person(models.Model):
    nome = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.nome)

def restrict_amount(value):
    if Person.objects.filter(person_car=value).count() >= 3:
        raise ValidationError('Team already has maximal amount of rounds (3)')

class Car(models.Model):
    COLOR_CHOICES = (
        ('Amarelo','Amarelo'),
        ('Azul','Azul'),
        ('Cinza','Cinza')
    )
    TYPE_CHOICES = (
        ('Hatch','Hatch'),
        ('Sedan','Sedan'),
        ('Conversível','Conversível')
    )
    pessoa = models.ForeignKey(Person,on_delete=models.CASCADE,related_name="person_car",validators=(restrict_amount, ))
    cor = models.CharField(max_length=50,choices=COLOR_CHOICES)
    modelo = models.CharField(max_length=50,choices=TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.modelo,self.cor)
    
    def clean(self):
        if Car.objects.filter(pessoa_id=self.pessoa_id).count() >= 3:
            raise ValidationError('{} já tem o máximo de carros permitidos'.format(self.pessoa))

carford/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy
from .models import *
from .filters import *

def Dashboard(request):
    if request.GET:
        filters = request.GET.copy()
        queryset = Person.objects.all().order_by('nome')
        filtro = PersonFilter(filters, queryset=queryset)
    else:
        filtro = PersonFilter(request.GET, queryset=Person.objects.all())
    return render(request,'dashboard.html',{'people':filtro})

class PersonCreateView(CreateView):
    model = Person
    template_name = 'add.html'
    fields = ['nome']
    success_url= reverse_lazy('carford:dashboard')

class CarCreateView(CreateView):
    model = Car
    template_name = 'add.html'
    fields = ['pessoa','modelo','cor']
    success_url= reverse_lazy('carford:dashboard')

templates/add.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="col col-11 mx-auto my-4">

        <form action="." method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Salvar
            </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock  %}

templates/add_person.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div class="col col-11 mx-auto my-4">

        <form action="/url/to/submit/" method="post" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button type="submit" class="btn btn-primary">
                Salvar
            </button>
            {% endbuttons %}
        </form>
    </div>
{% endblock  %}

templates/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Carford Car Shop</title>
    <link rel="icon" href="https://sp-ao.shortpixel.ai/client/to_webp,q_lossless,ret_img,w_32,h_32/https://advicehealth.com.br/wp-content/uploads/2019/06/favicon-1.png" sizes="32x32">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% block head %}
    {% endblock %}
</head>

<body>

    <main>

        <div class="container m-5 p-2 rounded mx-auto bg-light shadow">
            <!-- App title section -->
            <div class="row m-1 p-4">
                <div class="col">
                    <div class="p-1 h1 text-primary text-center mx-auto display-inline-block">
                        <a href="{% url 'carford:dashboard' %}">Carford Car Shop</a>
                    </div>
                </div>
            </div>
            <!-- Create todo section -->
            <div class="row m-1 p-3">
                {% comment %} <div class="col col-11 mx-auto">
                    <div class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center">
                        <div class="col">
                            <input class="form-control form-control-lg border-0 add-todo-input bg-transparent rounded"
                                type="text" placeholder="Adicionar ..">
                        </div>
                        <div class="col-auto m-0 px-2 d-flex align-items-center">
                            <label class="text-secondary my-2 p-0 px-1 view-opt-label due-date-label d-none">Due date not
                                set</label>
                            <i class="fa fa-calendar my-2 px-1 text-primary btn due-date-button" data-toggle="tooltip"
                                data-placement="bottom" title="Set a Due date"></i>
                            <i class="fa fa-calendar-times-o my-2 px-1 text-danger btn clear-due-date-button d-none"
                                data-toggle="tooltip" data-placement="bottom" title="Clear Due date"></i>
                        </div>
                        <div class="col-auto px-0 mx-0 mr-2">
                            <button type="button" class="btn btn-primary">Adicionar</button>
                        </div>
                    </div>
                </div> {% endcomment %}
            </div>
            
            {% block content %}{% endblock %}
        </div>
    </main>

</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}

{% block head %}

{% endblock %}

{% block content %}

<div class="row m-1 p-3">
    <div class="col col-11 mx-auto">
        <form class="row bg-white rounded shadow-sm p-2 add-todo-wrapper align-items-center justify-content-center">
            <div class="col">
                    {{ people.form.nome }}
            </div>
            <div class="col-auto m-0 px-2 d-flex align-items-center">
                <label class="text-secondary my-2 p-0 px-1 view-opt-label due-date-label d-none">Due date not
                    set</label>
                <i class="fa fa-calendar my-2 px-1 text-primary btn due-date-button" data-toggle="tooltip"
                    data-placement="bottom" title="Set a Due date"></i>
                <i class="fa fa-calendar-times-o my-2 px-1 text-danger btn clear-due-date-button d-none"
                    data-toggle="tooltip" data-placement="bottom" title="Clear Due date"></i>
            </div>
            <div class="col-auto px-0 mx-0 mr-2">
                <button type="submit" class="btn btn-primary">Pesquisar</button>
            </div>
        </form>
    </div>
</div>

<div class="p-2 mx-4 border-black-25 border-bottom"></div>


<div class="row m-1 p-3 px-5 justify-content-end">
    <div class="col-auto d-flex align-items-center">
        <a href="{% url 'carford:add_pessoa' %}" class="btn btn-primary">Adicionar Pessoa</a>
    </div>
    <div class="col-auto d-flex align-items-center px-1 pr-3">
        <a href="{% url 'carford:add_carro' %}" class="btn btn-primary">Adicionar Carro</a>
    </div>
</div>

<div class="row mt-3 mx-1 px-5 pb-3 w-80">
    <div class="col mx-auto">
        <!-- Todo Item 1 -->

        {% if people %}

        {% for person in people.qs %}
        <div class="my-3">

            <div class="row px-3 align-items-center todo-item rounded">

                <div class="col px-1 m-1 d-flex align-items-center">
                    <h3>{{person.nome}}</h3>
                </div>

                <div class="row todo-created-info">
                    <div class="col-auto d-flex align-items-center pr-2">
                        <i class="fa fa-info-circle my-2 px-2 text-black-50 btn" data-toggle="tooltip"
                            data-placement="bottom" title="" data-original-title="Created date"></i>
                        <label class="date-label my-2 text-black-50">{{person.created_at|date:"D d M Y"}}</label>
                    </div>
                </div>

            </div>
            <div class="col-auto m-1 p-0 px-3">
                {% if person.person_car.all %}
                {% for cartype in person.person_car.all %}
                <span
                    class="badge {% if cartype.cor == 'Amarelo' %}badge-warning {% elif cartype.cor == 'Azul' %}badge-primary {% elif cartype.cor == 'Cinza' %}badge-secondary{% endif %} p-2">{{cartype}}</span>
                {% endfor %}
                {% else %}
                <span class="badge badge-success p-2">Oportunidade de venda</span>
                {% endif %}
            </div>
        </div>
        {% endfor %}

        {% else %}
        <h2 class="text-center">Sem registros no momento</h2>
        {% endif %}


    </div>
</div>

{% endblock %}